// Required Vercel env vars:
//   GMAIL_CLIENT_ID      — Google Cloud Console > OAuth 2.0 Client
//   GMAIL_CLIENT_SECRET  — same client
//   GMAIL_REFRESH_TOKEN  — one-time OAuth flow (see docs)

export async function POST(request) {
  try {
      const data = await request.json();
          const { invoiceNum, phase, clientName, billToName, billToEmail,
                      signerName, signerEmail, grand, dueDate, fromName, fromEmail } = data;

                          const toEmail = billToEmail || signerEmail;
                              const toName  = billToName  || signerName || "Team";

                                  // ── 1. Get Gmail access token ──────────────────────────────────────────
                                      const tokenRes = await fetch("https://oauth2.googleapis.com/token", {
                                            method: "POST",
                                                  headers: { "Content-Type": "application/x-www-form-urlencoded" },
                                                        body: new URLSearchParams({
                                                                client_id:     process.env.GMAIL_CLIENT_ID,
                                                                        client_secret: process.env.GMAIL_CLIENT_SECRET,
                                                                                refresh_token: process.env.GMAIL_REFRESH_TOKEN,
                                                                                        grant_type:    "refresh_token",
                                                                                              }),
                                                                                                  });
                                                                                                      if (!tokenRes.ok) {
                                                                                                            const err = await tokenRes.text();
                                                                                                                  return Response.json({ error: "Gmail token error: " + err }, { status: 500 });
                                                                                                                      }
                                                                                                                          const { access_token } = await tokenRes.json();

                                                                                                                              // ── 2. Generate the invoice PDF ────────────────────────────────────────
                                                                                                                                  const origin = new URL(request.url).origin;
                                                                                                                                      const pdfRes = await fetch(`${origin}/api/generate-pdf`, {
                                                                                                                                            method: "POST",
                                                                                                                                                  headers: { "Content-Type": "application/json" },
                                                                                                                                                        body: JSON.stringify({ invoiceData: data }),
                                                                                                                                                            });
                                                                                                                                                                if (!pdfRes.ok) {
                                                                                                                                                                      return Response.json({ error: "PDF generation failed" }, { status: 500 });
                                                                                                                                                                          }
                                                                                                                                                                              const pdfBase64 = Buffer.from(await pdfRes.arrayBuffer()).toString("base64");

                                                                                                                                                                                  // ── 3. Build RFC 2822 email with PDF attached ──────────────────────────
                                                                                                                                                                                      const subject  = `Invoice #${invoiceNum} — ${phase} | $${grand} USD`;
                                                                                                                                                                                          const bodyText = [
                                                                                                                                                                                                `Hi ${toName},`,
                                                                                                                                                                                                      ``,
                                                                                                                                                                                                            `Please find Invoice #${invoiceNum} attached for your reference.`,
                                                                                                                                                                                                                  ``,
                                                                                                                                                                                                                        `  Client:    ${clientName}`,
                                                                                                                                                                                                                              `  Phase:     ${phase}`,
                                                                                                                                                                                                                                    `  Amount:    $${grand} USD`,
                                                                                                                                                                                                                                          `  Due Date:  ${dueDate}`,
                                                                                                                                                                                                                                                ``,
                                                                                                                                                                                                                                                      `Please don't hesitate to reach out if you have any questions.`,
                                                                                                                                                                                                                                                            ``,
                                                                                                                                                                                                                                                                  `Best,`,
                                                                                                                                                                                                                                                                        fromName,
                                                                                                                                                                                                                                                                              `AIVC, Inc. | ${fromEmail}`,
                                                                                                                                                                                                                                                                                  ].join("\n");

                                                                                                                                                                                                                                                                                      const boundary = `aivc_${Date.now()}`;
                                                                                                                                                                                                                                                                                          const raw = [
                                                                                                                                                                                                                                                                                                `MIME-Version: 1.0`,
                                                                                                                                                                                                                                                                                                      `To: ${toEmail}`,
                                                                                                                                                                                                                                                                                                            `From: ${fromName} <${fromEmail}>`,
                                                                                                                                                                                                                                                                                                                  `Subject: ${subject}`,
                                                                                                                                                                                                                                                                                                                        `Content-Type: multipart/mixed; boundary="${boundary}"`,
                                                                                                                                                                                                                                                                                                                              ``,
                                                                                                                                                                                                                                                                                                                                    `--${boundary}`,
                                                                                                                                                                                                                                                                                                                                          `Content-Type: text/plain; charset="UTF-8"`,
                                                                                                                                                                                                                                                                                                                                                ``,
                                                                                                                                                                                                                                                                                                                                                      bodyText,
                                                                                                                                                                                                                                                                                                                                                            ``,
                                                                                                                                                                                                                                                                                                                                                                  `--${boundary}`,
                                                                                                                                                                                                                                                                                                                                                                        `Content-Type: application/pdf; name="Invoice_${invoiceNum}.pdf"`,
                                                                                                                                                                                                                                                                                                                                                                              `Content-Disposition: attachment; filename="Invoice_${invoiceNum}.pdf"`,
                                                                                                                                                                                                                                                                                                                                                                                    `Content-Transfer-Encoding: base64`,
                                                                                                                                                                                                                                                                                                                                                                                          ``,
                                                                                                                                                                                                                                                                                                                                                                                                pdfBase64,
                                                                                                                                                                                                                                                                                                                                                                                                      ``,
                                                                                                                                                                                                                                                                                                                                                                                                            `--${boundary}--`,
                                                                                                                                                                                                                                                                                                                                                                                                                ].join("\r\n");

                                                                                                                                                                                                                                                                                                                                                                                                                    const encoded = Buffer.from(raw).toString("base64")
                                                                                                                                                                                                                                                                                                                                                                                                                          .replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

                                                                                                                                                                                                                                                                                                                                                                                                                              // ── 4. Create Gmail draft ──────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                  const draftRes = await fetch(
                                                                                                                                                                                                                                                                                                                                                                                                                                        "https://gmail.googleapis.com/gmail/v1/users/me/drafts",
                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Authorization: `Bearer ${access_token}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: JSON.stringify({ message: { raw: encoded } }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!draftRes.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const err = await draftRes.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Response.json({ error: "Gmail draft error: " + err }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const draft = await draftRes.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return Response.json({ status: "draft_created", draftId: draft.id });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return Response.json({ error: err.message }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }